language: python
python:
  - 2.7
  - 3.4
  - 3.5
  - 3.6
env:
matrix:
  fast_finish: true
  include:
    - python: 2.7
      env: TOXENV=py27-unpinned
    - python: 3.6
      env: TOXENV=flake8
    - python: 3.6
      env: TOXENV=py36-unpinned
    - python: 3.6
      env: TOXENV=black
    # see the following issue on why 3.7 is weirdo
    # https://github.com/travis-ci/travis-ci/issues/9815
    - python: 3.7
      dist: xenial
      sudo: true
  allow_failures:
    # until the entire code base is properly formatted
    # allow failures to occur here rather than doing a
    # big all at once reformat that could hide errors
    - env: TOXENV=black
install:
- pip install -r requirements-travis.txt
script:
- flaskbb translations compile
- tox
after_success:
- coverage combine tests
- coveralls
notifications:
  webhooks: https://www.travisbuddy.com/
  on_success: never
deploy:
  provider: pypi
  user: sh4nks
  password:
    secure: l5aa7UjggBWYD4+EXTrgKVDB+0WcinC/DKJmAwfIGF54BtzuRz5dPyc3VLdZb2OKxbtK9vBSgDLghqsWh4jXS0KSuUmEzS7LgCU6XBocIoAC8VdqgLLLEEDWJNtib5R+pk8imXbGk9lD2O7fS8b6/2/pDM1yKRpzU76SOyICpyo=
  distributions: sdist bdist_wheel
  on:
    tags: true
    all_branches: true
    repo: flaskbb/flaskbb
    python: '3.7'
